(() => {
"use strict";
const $=id=>document.getElementById(id),root=$("gameRoot"),canvas=$("gameCanvas"),ctx=canvas.getContext("2d");
const ui={hud:$("hud"),start:$("startScreen"),count:$("countdown"),countText:$("countdownText"),pause:$("pauseScreen"),bake:$("bakeScreen"),bakeBar:$("bakeBar"),result:$("resultScreen"),hearts:$("hearts"),best:$("bestScore"),score:$("score"),time:$("time"),rank:$("rank"),bar:$("progressBar"),stage:$("pizzaStage"),missionText:$("missionText"),missionProgress:$("missionProgress"),fever:$("feverBanner"),combo:$("comboBanner"),title:$("resultTitle"),resultRank:$("resultRank"),message:$("resultMessage"),success:$("successBox"),code:$("successCode"),startBtn:$("startBtn"),retryBtn:$("retryBtn"),pauseBtn:$("pauseBtn"),resumeBtn:$("resumeBtn"),soundBtn:$("soundBtn")};
const sources={onion:"onion.png",tomato:"tomato.png",cheese:"cheese.png",sweetpotato:"sweetpotato.png",dough:"dough.png",potato:"potato.png",bomb:"bomb.png",player:"player_box.png"};
const imgs={};for(const [k,v] of Object.entries(sources)){const i=new Image();i.src="./assets/images/"+v;imgs[k]=i}
const normal=["onion","tomato","cheese","sweetpotato","dough","potato"];
const missionPool=[{type:"collect",key:"onion",target:6,text:"양파 6개 받기"},{type:"collect",key:"sweetpotato",target:6,text:"고구마 6개 받기"},{type:"collect",key:"potato",target:6,text:"감자 6개 받기"},{type:"combo",target:10,text:"10콤보 달성하기"}];
let W=0,H=0,D=1,state="ready",last=0,spawn=0,pointer=null,items=[],particles=[],texts=[],player=null,audio=null,sound=true,game={};
const rnd=(a,b)=>Math.random()*(b-a)+a,clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),sleep=m=>new Promise(r=>setTimeout(r,m));
function rank(s){if(s>=700)return"SSS";if(s>=600)return"SS";if(s>=500)return"S";if(s>=400)return"A";if(s>=300)return"B";return"C"}
function stage(s){if(s<100)return"🍞 도우 준비";if(s<200)return"🍅 소스 완성";if(s<300)return"🧀 치즈 듬뿍";if(s<400)return"🥔 토핑 추가";if(s<500)return"🔥 오븐에서 굽는 중";return"🍕 피자 완성!"}
function profile(e){if(e<8)return{gap:[.22,.30],bomb:.20,min:330,max:470};if(e<16)return{gap:[.17,.24],bomb:.28,min:420,max:590};if(e<22)return{gap:[.13,.19],bomb:.36,min:520,max:700};return{gap:[.10,.15],bomb:.44,min:620,max:860}}
function unlock(){if(!audio){const A=window.AudioContext||window.webkitAudioContext;if(A)audio=new A()}if(audio&&audio.state==="suspended")audio.resume().catch(()=>{})}
function beep(f,d=.06,t="sine",v=.035){if(!sound||!audio)return;const o=audio.createOscillator(),g=audio.createGain();o.frequency.value=f;o.type=t;g.gain.setValueAtTime(v,audio.currentTime);g.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+d);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+d)}
function resize(){D=Math.min(devicePixelRatio||1,2);W=innerWidth;H=innerHeight;canvas.width=W*D;canvas.height=H*D;ctx.setTransform(D,0,0,D,0,0);const pw=clamp(W*.34,220,520),ph=pw/(1600/824);if(!player)player={x:W/2,targetX:W/2,tilt:0,targetTilt:0};Object.assign(player,{w:pw,h:ph,y:H-ph*.86});player.x=player.targetX=clamp(player.x,pw*.32,W-pw*.32)}
function newMission(){const m={...missionPool[Math.floor(Math.random()*missionPool.length)]};m.progress=0;m.done=false;return m}
function reset(){game={score:0,lives:3,elapsed:0,remaining:30,combo:0,best:Number(localStorage.getItem("pizzaCompleteBest")||0),gold:0,mission:newMission(),lastBomb:-99,missionRewarded:false};items=[];particles=[];texts=[];spawn=0;player.x=player.targetX=W/2;player.tilt=player.targetTilt=0;updateHud()}
async function start(){if(state==="countdown"||state==="playing")return;unlock();reset();ui.start.classList.add("is-hidden");ui.result.classList.add("is-hidden");ui.hud.classList.remove("is-hidden");ui.count.classList.remove("is-hidden");state="countdown";for(const v of["3","2","1","START!"]){ui.countText.textContent=v;beep(v==="START!"?700:440,.08,"square",.04);await sleep(v==="START!"?450:650)}ui.count.classList.add("is-hidden");state="playing";last=performance.now();requestAnimationFrame(loop)}
function make(type=null){const p=profile(game.elapsed);if(!type)type=Math.random()<p.bomb?"bomb":normal[Math.floor(Math.random()*normal.length)];const size=W<600?rnd(48,66):rnd(58,78);return{type,x:rnd(size,W-size),y:-size-rnd(0,45),size,speed:rnd(p.min,p.max),rot:rnd(-.3,.3),spin:rnd(-5.5,5.5),wave:rnd(0,6.28),ws:type==="bomb"?rnd(6,9):rnd(2.5,4.5),amp:type==="bomb"?rnd(18,38):rnd(5,12)}}
function spawnItems(){const p=profile(game.elapsed);items.push(make());if(Math.random()<.1)items.push(make());if(game.gold<3&&game.elapsed>4&&Math.random()<.05){items.push(make("golden"));game.gold++}spawn=rnd(...p.gap)}
function loop(n){if(state!=="playing")return;const dt=Math.min((n-last)/1000,.034);last=n;game.elapsed+=dt;game.remaining-=dt;if(game.remaining<=0){game.remaining=0;finish();return}const follow=Math.min(1,dt*(W<700?22:15));player.x+=(player.targetX-player.x)*follow;player.tilt+=(player.targetTilt-player.tilt)*Math.min(1,dt*11);player.targetTilt*=Math.pow(.04,dt);spawn-=dt;if(spawn<=0)spawnItems();updateItems(dt);updateEffects(dt);updateHud();draw();requestAnimationFrame(loop)}
function updateItems(dt){for(let i=items.length-1;i>=0;i--){const it=items[i];it.y+=it.speed*dt;it.rot+=it.spin*dt;it.wave+=it.ws*dt;const dx=it.x+Math.sin(it.wave)*it.amp,catchY=player.y+player.h*.2;const hit=Math.abs(dx-player.x)<player.w*.29+it.size*.25&&it.y+it.size*.34>=catchY&&it.y-it.size*.24<=player.y+player.h*.5;if(hit){collect(it,dx);items.splice(i,1)}else if(it.y-it.size>H){if(it.type!=="bomb")game.combo=0;items.splice(i,1)}}}
function mult(){return game.remaining<=8?2:1}
function showCombo(text){ui.combo.textContent=text;ui.combo.classList.remove("is-hidden");setTimeout(()=>ui.combo.classList.add("is-hidden"),700)}
function collect(it,x){if(it.type==="bomb"){if(game.elapsed-game.lastBomb<.35)return;game.lastBomb=game.elapsed;game.score=Math.max(0,game.score-10);game.lives--;game.combo=0;addText(x,player.y,"BOOM! -10",true,1.25);burst(x,player.y+10,30,true);root.classList.remove("bomb-hit");void root.offsetWidth;root.classList.add("bomb-hit");setTimeout(()=>root.classList.remove("bomb-hit"),460);beep(85,.18,"sawtooth",.08);if(navigator.vibrate)navigator.vibrate([80,35,110]);if(game.lives<=0)finish();return}
if(it.type==="golden"){const p=50*mult();game.score+=p;addText(x,player.y-8,`✨ GOLD +${p} ✨`,false,1.25);burst(x,player.y,28,false);beep(940,.14,"sine",.06);return}
const p=10*mult();game.score+=p;game.combo++;if(game.mission.type==="collect"&&game.mission.key===it.type)game.mission.progress++;if(game.mission.type==="combo")game.mission.progress=Math.max(game.mission.progress,game.combo);if(!game.mission.done&&game.mission.progress>=game.mission.target){game.mission.done=true;game.score+=50;addText(W/2,H*.34,"MISSION +50",false,1.15)}
addText(x,player.y-10,`+${p}`,false,1);burst(x,player.y+4,10,false);beep(520+Math.min(game.combo,15)*18,.05);
if(game.combo===5){game.score+=20;showCombo("COMBO +20")}else if(game.combo===10){game.score+=50;showCombo("PIZZA MASTER +50")}else if(game.combo===15){game.score+=100;showCombo("LEGEND +100")}}
function addText(x,y,text,bad=false,scale=1){texts.push({x,y,text,bad,scale,life:.95,max:.95})}
function burst(x,y,count,explosion){for(let i=0;i<count;i++)particles.push({x,y,vx:rnd(-220,220),vy:rnd(-270,80),g:rnd(260,460),size:rnd(3,10),life:rnd(.45,.9),max:.9,color:explosion?(Math.random()>.5?"#ff6a00":"#ffd83d"):"#ffe448"})}
function updateEffects(dt){for(let i=texts.length-1;i>=0;i--){const t=texts[i];t.life-=dt;t.y-=58*dt;if(t.life<=0)texts.splice(i,1)}for(let i=particles.length-1;i>=0;i--){const p=particles[i];p.life-=dt;p.vy+=p.g*dt;p.x+=p.vx*dt;p.y+=p.vy*dt;if(p.life<=0)particles.splice(i,1)}}
function updateHud(){ui.score.textContent=game.score;ui.time.textContent=Math.max(0,Math.ceil(game.remaining));ui.rank.textContent=rank(game.score);ui.bar.style.width=Math.min(100,game.score/500*100)+"%";ui.stage.textContent=stage(game.score);ui.best.textContent=game.best;ui.hearts.innerHTML="";for(let i=0;i<3;i++){const h=document.createElement("span");h.textContent="❤️";h.className="heart"+(i>=game.lives?" off":"");ui.hearts.appendChild(h)}ui.missionText.textContent=game.mission.text;ui.missionProgress.textContent=`${Math.min(game.mission.progress,game.mission.target)} / ${game.mission.target}`;const fever=game.remaining<=8;ui.fever.classList.toggle("is-hidden",!fever);root.classList.toggle("fever-mode",fever)}
function drawItem(it){const dx=it.x+Math.sin(it.wave)*it.amp;ctx.save();ctx.translate(dx,it.y);ctx.rotate(it.rot);if(it.type==="golden"){ctx.shadowColor="#ffd700";ctx.shadowBlur=30;ctx.font=`900 ${it.size*.76}px Arial`;ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText("🍕",0,0)}else{const im=imgs[it.type];if(im&&im.complete){ctx.shadowColor="#0005";ctx.shadowBlur=9;ctx.shadowOffsetY=6;ctx.drawImage(im,-it.size/2,-it.size/2,it.size,it.size)}}ctx.restore()}
function drawPlayer(){const im=imgs.player;if(!im||!im.complete)return;ctx.save();ctx.translate(player.x,player.y+player.h/2);ctx.rotate(player.tilt);ctx.shadowColor="#0006";ctx.shadowBlur=16;ctx.shadowOffsetY=8;ctx.drawImage(im,-player.w/2,-player.h/2,player.w,player.h);ctx.restore()}
function draw(){ctx.clearRect(0,0,W,H);for(const it of items)drawItem(it);drawPlayer();for(const p of particles){ctx.save();ctx.globalAlpha=clamp(p.life/p.max,0,1);ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(p.x,p.y,p.size,0,6.28);ctx.fill();ctx.restore()}for(const t of texts){ctx.save();ctx.globalAlpha=clamp(t.life/t.max,0,1);ctx.translate(t.x,t.y);ctx.scale(t.scale,t.scale);ctx.font="900 30px Arial";ctx.textAlign="center";ctx.lineWidth=6;ctx.strokeStyle=t.bad?"#fff":"#d91e24";ctx.fillStyle=t.bad?"#151515":"#ffe448";ctx.strokeText(t.text,0,0);ctx.fillText(t.text,0,0);ctx.restore()}}
async function finish(){if(state==="finished")return;state="finished";game.best=Math.max(game.best,game.score);localStorage.setItem("pizzaCompleteBest",game.best);const ok=game.score>=500,r=rank(game.score);if(ok){ui.bake.classList.remove("is-hidden");ui.bakeBar.style.width="0";await sleep(80);ui.bakeBar.style.transition="width 1.2s linear";ui.bakeBar.style.width="100%";await sleep(1250);beep(1040,.22,"sine",.06);ui.bake.classList.add("is-hidden")}ui.title.textContent=ok?"딩! 피자 완성!":"도전 종료!";ui.resultRank.textContent=r;ui.message.innerHTML=`최종 점수 <strong>${game.score}점</strong><br>${ok?"선명희피자가 맛있게 완성됐어요!":"500점에 다시 도전해보세요."}`;ui.success.classList.toggle("is-hidden",!ok);if(ok){const d=new Date(),dc=String(d.getFullYear()).slice(-2)+String(d.getMonth()+1).padStart(2,"0")+String(d.getDate()).padStart(2,"0");ui.code.textContent=`PZ-${dc}-${Math.floor(10000+Math.random()*90000)}`;if(navigator.vibrate)navigator.vibrate([60,35,60,35,150])}ui.result.classList.remove("is-hidden")}
function move(x){if(state!=="playing")return;const prev=player.targetX;player.targetX=clamp(x,player.w*.32,W-player.w*.32);player.targetTilt=clamp((player.targetX-prev)/430,-.09,.09)}
canvas.addEventListener("pointerdown",e=>{pointer=e.pointerId;canvas.setPointerCapture?.(e.pointerId);move(e.clientX)},{passive:true});canvas.addEventListener("pointermove",e=>{if(pointer===null||pointer===e.pointerId)move(e.clientX)},{passive:true});canvas.addEventListener("pointerup",e=>{if(e.pointerId===pointer)pointer=null},{passive:true});
ui.startBtn.addEventListener("click",start);ui.retryBtn.addEventListener("click",()=>{ui.result.classList.add("is-hidden");ui.start.classList.remove("is-hidden");ui.hud.classList.add("is-hidden");root.classList.remove("fever-mode","bomb-hit");state="ready"});ui.pauseBtn.addEventListener("click",()=>{if(state==="playing"){state="paused";ui.pause.classList.remove("is-hidden")}});ui.resumeBtn.addEventListener("click",()=>{if(state==="paused"){ui.pause.classList.add("is-hidden");state="playing";last=performance.now();requestAnimationFrame(loop)}});ui.soundBtn.addEventListener("click",()=>{sound=!sound;ui.soundBtn.textContent=sound?"🔊":"🔇";if(sound)unlock()});document.addEventListener("visibilitychange",()=>{if(document.hidden&&state==="playing")ui.pauseBtn.click()});addEventListener("resize",resize);resize();reset();
})();